#+TITLE: Shell Script Introduction
#+AUTHOR: vinci
#+OPTIONS: toc

* Table of Contents :toc:
- [[#variables][Variables]]
- [[#command-line-arguments][Command Line Arguments]]
- [[#read-inputs][Read Inputs]]
- [[#arithmetic][Arithmetic]]

* Variables
#+begin_src shell
  variable_name=variable-value

  mkdir $variable_name
#+end_src

Initializing variables doesn't need ~$~. We just use the ~$~ symbol on usage.

Take note as well that variable names can only contain *alphanumeric or underscores*.

We can also store the output of a command and put it in a variable.
#+begin_src shell
  var=$(echo "Hello World!")

  echo "Var value: $var"
#+end_src

* Command Line Arguments
To have the variable name be taken from the argument, we can just specify:
#+begin_src shell
  variable_name=$1

  mkdir $variable_name
#+end_src

Then running ~<command> test~ will execute ~mkdir test~.

* Read Inputs
To read an input when executing the shell script we use the ~read~ statement:
#+begin_src shell
  read variable_name
#+end_src

To add a prompt we add the ~-p~ flag:
#+begin_src shell
  read -p "Enter variable:" variable_name
#+end_src

* Arithmetic
There are multiple ways to implement arithmetic operations in the shell.

*** expr
#+begin_src shell
  expr 1 + 1
#+end_src

The ~expr~ command should separate the operands and operators with a space.

When performing multiplication, we must use ~\*~ instead of ~*~ as the star symbol is a reserved character for regex in the shell.

*** Double Parentheses
#+begin_src shell
  echo $((A + B))
#+end_src

Using double paretheses should be used with echo or assign it to a variable.

For multiplication, we can just use ~*~.

*** bc
For floating point numbers we utilize the ~bc~ command.

Usage:
#+begin_src shell
  echo $A / $B | bc -l
#+end_src

The ~-l~ flag is needed to generate floating point results as it loads the math library to enable advanced math functions usage.
