#+TITLE: Functions
#+AUTHOR: vinci
#+OPTIONS: toc

* Table of Contents :toc:
- [[#defining-and-calling-functions][Defining and Calling Functions]]
  - [[#function-definitions][Function Definitions]]
  - [[#function-calls][Function Calls]]
  - [[#function-declarations][Function Declarations]]
- [[#arguments][Arguments]]
  - [[#argument-conversions][Argument Conversions]]
  - [[#array-arguments][Array Arguments]]
  - [[#variable-length-array-parameters][Variable-Length Array Parameters]]
  - [[#using-static-in-array-parameter-declarations][Using ~static~ in Array Parameter Declarations]]
  - [[#compound-literals][Compound Literals]]
- [[#the-return-statement][The ~return~ Statement]]
- [[#program-termination][Program Termination]]
  - [[#the-exit-function][The ~exit~ Function]]
- [[#recursion][Recursion]]
  - [[#the-quicksort-algorithm][The Quicksort Algorithm]]

* Defining and Calling Functions
A function that returns a value: [[file:sample-program/average.c][average.c]].
A function that does not return a value: [[file:sample-program/countdown.c][countdown.c]].
A function that does not return a value and does not need arguments: [[file:sample-program/pun2.c][pun2.c]].

** Function Definitions
General form of a function definition:
#+begin_src
  return-type function-name ( parameters )
  {
    declarations
    statements
  }
#+end_src

*C99* requires a return type while *C89* assumes a return type of ~int~ if none is specified.

** Function Calls
Calling a non-void functions produces a value and can be assigned to a variable.

Example: [[file:sample-program/prime.c][prime.c]]

** Function Declarations
When we call a function before it is defined, the compiler makes implicit decisions on the return type, arguments, etc. When it is defined, the compiler then throws an error as it does not have the proper attributes when it was /implicitly declared/.

We can avoid this by defining all the functions before it is called. In a large program however this is hard so C introduces *function declaration* which gives the compiler a brief glimpse at a function whose full definition will appear later.

Syntax: ~return-type function-name ( parameters ) ;~

Sample program:
#+begin_src C
  #include <stdio.h>
  double average(double a, double b); /* DECLARATION */

  int main(void)
  {
    double x, y, z;

    printf("Enter three numbers: ");
    scanf("%lf%lf%lf", &x, &y, &z);
    printf("Average of %g and &g: %g\n", x, y, average(x, y));
    printf("Average of %g and &g: %g\n", y, z, average(y, z));
    printf("Average of %g and &g: %g\n", x, z, average(x, z));

    return 0;
  }

  double average(double a, double b) /* DEFINITION */
  {
    return (a + b) / 2;
  }
#+end_src

* Arguments
/Parameters/ are the dummy names appearing in function definitions. /Arguments/ are expressions that appear in function calls.

** Argument Conversions
C allows function calls wherein the types of the arguments doesn't match the parameter types.

Rules on how arguments are converted:
1. *The compiler has encountered a prototype prior to the call.* The value of each argument is implicitly converted to the type of the corresponding parameter as if by assignment.
2. *The compiler has not encountered a prototype prior to the call.* The compiler performs /default argument promotions/:
   - ~float~ arguments are converted to ~double~
   - Integral promotions are performed; ~char~ and ~short~ are converted to ~int~.

** Array Arguments
When a function parameter, the array length is usually left unspecified. The function however won't know how long the array is, so we supply another parameter that specifies the array length.

#+begin_src C
  int sum_array(int a[], int n) {
    int i, sum = 0;
    for (i = 0; i < n; i++) {
      sum += a[i];
    }
  }
#+end_src

When passing an array name into a function when it is already initialized, we omit ~[]~.

An important note to remember is that the function has no way to check if we passed the correct array length and we can leverage this by having the option to tell the function that the array is smaller than it really is. Just be careful not to pass a larger number than the array length.

When using arrays as arguments, the function is allowed to change the elements of the array parameter.

When using multidimensional arrays, only the length of the first dimension can be omitted when the parameter is declared.

#+begin_src C
  #define LEN 10

  int sum_two_dimensional_array(int a[][LEN], int n)
  {
    int i, j, sum = 0;

    for (i = 0; i < n; i++)
      for (j = 0; j < LEN; j++)
        sum += a[i][j];

    return sum;
  }
#+end_src

We can utilize the use of arrays of pointers to work around not being able to pass an arbitraty number of columns in multidimensional arrays.

** Variable-Length Array Parameters
For C99, the length of an array can be specified using a non-constant expression and VLAs can also be parameters.

#+begin_src c
  int sum_array(int n, int a[n]);
#+end_src

Notice that the first parameter ~n~ that specifies the length of the second parameter is now at the first because the compiler need to "see" ~n~ first before it can be used.

Order is important when VLA parameters are used.

We can also do:
#+begin_src c
  int sum_array(int n, int a[*]);

  int sum_array(int, int[*]);
#+end_src

The ~*~ provides a clue that the length of the array is related to the parameters that come earlier in the list. This is because parameter names are optional in function declarations.

Using VLA are most useful for multidimensional arrays as we can generalize the function to any number of columns.
#+begin_src c
  int sum_two_dimensional_array(int n, int m, int a[n][m])
  {
    int i, j, sum = 0;
    for (i = 0; i < n; i++)
      for (j = 0; j < m; j++)
        sum += a[i][j];

    return sum;
  }
#+end_src

The prototypes for this function include the ff:
#+begin_src c
  int sum_two_dimensional_array(int n, int m, int a[n][m]);
  int sum_two_dimensional_array(int n, int m, int a[*][*]);
  int sum_two_dimensional_array(int n, int m, int a[][m]);
  int sum_two_dimensional_array(int n, int m, int a[][*]);
#+end_src

** Using ~static~ in Array Parameter Declarations
~static~ is used to indicate that the value will never change.

Using ~static~ has no effect on the behavior of the program. It is just a hint that may allow the compiler to generate faster instructions for accessing the array.

#+begin_src c
  int sum_array(int a[static 3], int n);
#+end_src

Note that if an array parameter has > 1 dimensions then ~static~ can only be used in the 1st dimension.

** Compound Literals
Compound literals are unnamed arrays that is created on the fly by specifying the elements it contains.

#+begin_src c
  total = sum_array((int []){3, 0, 3, 4, 1}, 5);
#+end_src

We can also use arbitrary expressions for the elements for compound literals.
#+begin_src c
  total = sum_array((int []){2 * i, i + j, j * k}, 5);
#+end_src

A compound literal can be made read-only by adding the word ~const~.

* The ~return~ Statement
A non-void function must use the ~return~ statement to specify what value if will return.

Example use cases:
#+begin_src c
  return 0;
  return n >= 0 ? n : 0;
#+end_src

* Program Termination
Take note that omitting a return type of function is not legal.

It is also not best practice to omit ~void~ in ~main~'s parameter list. (~main~ sometimes does have two parameters named ~argc~ and ~argv~).

It is a good practice to always return a /status code/ even if there is no plans to use it since it is good for program testing.

** The ~exit~ Function
~exit~ belongs to ~<stdlib.h>~ and its arguments has the same meaning with ~main~'s return value which is indicating the programs status at termination.

#+begin_src c
  // normal termintation
  exit(0);
  exit(EXIT_SUCCESS);

  // abnormal termination
  exit(EXIT_FAILURE)
#+end_src

Basically, ~return <expression>~ == ~exit(<expression>)~.

The difference is that ~exit~ causes the program termination regardless of which function calls it, while ~return~ causes program termination only when it appears in the ~main~ function.

* Recursion
A function is recursive if it calls itself.

#+begin_src c
  // computing n factorial
  int fact(int n)
  {
    if (n <= 1)
      return 1;
    else
      return n * fact(n - 1);
  }
#+end_src

#+begin_src c
  // computing x^n = x * x^(n-1)
  int power(int x, int n)
  {
    if (n == 0)
      return 1;
    else
      return x * power(x, n - 1);
  }

  int power(int x, int n)
  {
    return n == 0 ? 1 : x * power(x, n - 1);
  }
#+end_src

All recursive functions need a *termination condition* to prevent infinite recursion.

** The Quicksort Algorithm
In practice, recursion often arises naturally as a result of an algorithm design technique known as /divide-and-conquer/ in which a large problem is divided into smaller pieces and then tackled by the same algorithm.

*Quicksort* is an example of the divide-and-conquer strategy and goes as follows (for simplicity, assume that the array being sorted is indexed from 1 to /n/):
1. Choose an array element ~e~ (the "partitioning element"), then rearrange the array so that the elements ~1, ..., i - 1~ are less than or equal to ~e~, the element ~i~ contains ~e~, and the elements ~i + 1, ..., n~ are greater than or equal to ~e~.
2. Sort elements ~1, ..., i - 1~ by using Quicksort recursively.
3. Sort elements ~i + 1, ..., n~ by using Quicksort recursively.

The algorithm relies on two "markers" named /low/ and /high/, which keep track of the positions within the array.

Initially /low/ points to the first element of the array and /high/ points to the last element.

We start by copying the first element (partitioning element) into a temporary location elsewhere, leaving a "hole" in the array.

We then move /high/ across the array from right to left until it points to an element that is smaller than the partitioning element.

We copy the element to the "hole" that the /low/ points to which creates a new "hole" pointed at by /high/.

We then move /low/ from left to right looking for an element that is larger than the partitioning element.

We find one, we copy it to the hole /high/ points to, then the process repeats with /low/ and /high/ taking turns until they meet somewhere in the middle of the array.

At that point, both will point at a hole and all we need is to copy the partitioning element into the hole.

Example C code using Quicksort: 
